apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 10
  selector:
    matchLabels:
      team: security
  template:
    metadata:
      labels:
        team: security
    spec:
      containers:
      - name: redis
        image: redis:alpine
